CREATE TABLE IF NOT EXISTS "comment_lens_repository_installation" ("id" text PRIMARY KEY NOT NULL, "installation_id" integer NOT NULL, "owner_login" text NOT NULL, "owner_id" text NOT NULL, "repository_id" text NOT NULL, "repository" text NOT NULL, "default_branch" text NOT NULL, "is_private" boolean DEFAULT false NOT NULL, "last_verified_at" timestamptz, "created_at" timestamptz DEFAULT now() NOT NULL, "expires_at" timestamptz);
CREATE UNIQUE INDEX IF NOT EXISTS "comment_lens_installation_repo_idx" ON "comment_lens_repository_installation" ("installation_id", "repository_id");
CREATE TABLE IF NOT EXISTS "comment_lens_comment_identity" ("id" text PRIMARY KEY NOT NULL, "repository_installation_id" text NOT NULL, "path" text NOT NULL, "kind" text NOT NULL, "normalized_body" text NOT NULL, "symbol_anchor" text, "placement" text NOT NULL, "collision_index" integer DEFAULT 0 NOT NULL, "created_at" timestamptz DEFAULT now() NOT NULL);
ALTER TABLE "comment_lens_scan" ADD COLUMN IF NOT EXISTS "owner_id" text;
ALTER TABLE "comment_lens_scan" ADD COLUMN IF NOT EXISTS "owner_login" text;
ALTER TABLE "comment_lens_scan" ADD COLUMN IF NOT EXISTS "repository_installation_id" text;
ALTER TABLE "comment_lens_scan" ADD COLUMN IF NOT EXISTS "resolved_commit" text;
ALTER TABLE "comment_lens_scan" ADD COLUMN IF NOT EXISTS "workflow_run_id" text;
ALTER TABLE "comment_lens_scan" ADD COLUMN IF NOT EXISTS "workflow_dispatch_id" text;
ALTER TABLE "comment_lens_scan" ADD COLUMN IF NOT EXISTS "config_hash" text;
ALTER TABLE "comment_lens_scan" ADD COLUMN IF NOT EXISTS "extractor_version" text;
ALTER TABLE "comment_lens_scan" ADD COLUMN IF NOT EXISTS "parser_versions" jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE "comment_lens_scan" ADD COLUMN IF NOT EXISTS "file_count" integer DEFAULT 0 NOT NULL;
ALTER TABLE "comment_lens_scan" ADD COLUMN IF NOT EXISTS "chunk_count" integer DEFAULT 0 NOT NULL;
ALTER TABLE "comment_lens_scan" ADD COLUMN IF NOT EXISTS "content_sha256" text;
ALTER TABLE "comment_lens_scan" ADD COLUMN IF NOT EXISTS "retention_until" timestamptz;
ALTER TABLE "comment_lens_comment" ADD COLUMN IF NOT EXISTS "identity_id" text;
ALTER TABLE "comment_lens_comment" ADD COLUMN IF NOT EXISTS "placement" text DEFAULT 'standalone' NOT NULL;
ALTER TABLE "comment_lens_comment" ADD COLUMN IF NOT EXISTS "stale" boolean DEFAULT false NOT NULL;
ALTER TABLE "comment_lens_comment" ADD COLUMN IF NOT EXISTS "protected" boolean DEFAULT false NOT NULL;
ALTER TABLE "comment_lens_comment" ADD COLUMN IF NOT EXISTS "generated" boolean DEFAULT false NOT NULL;
ALTER TABLE "comment_lens_comment" ADD COLUMN IF NOT EXISTS "license" boolean DEFAULT false NOT NULL;
ALTER TABLE "comment_lens_comment" ADD COLUMN IF NOT EXISTS "todo_only" boolean DEFAULT false NOT NULL;
ALTER TABLE "comment_lens_comment" ADD COLUMN IF NOT EXISTS "author_name" text;
ALTER TABLE "comment_lens_comment" ADD COLUMN IF NOT EXISTS "author_email" text;
ALTER TABLE "comment_lens_chunk" ADD COLUMN IF NOT EXISTS "sequence" integer DEFAULT 0 NOT NULL;
ALTER TABLE "comment_lens_chunk" ADD COLUMN IF NOT EXISTS "total_chunks" integer DEFAULT 1 NOT NULL;
ALTER TABLE "comment_lens_chunk" ADD COLUMN IF NOT EXISTS "payload_sha256" text DEFAULT '' NOT NULL;
ALTER TABLE "comment_lens_review" ADD COLUMN IF NOT EXISTS "identity_id" text;
ALTER TABLE "comment_lens_review" ADD COLUMN IF NOT EXISTS "owner_id" text;
ALTER TABLE "comment_lens_assessment" ADD COLUMN IF NOT EXISTS "identity_id" text;
ALTER TABLE "comment_lens_assessment" ADD COLUMN IF NOT EXISTS "owner_id" text;
ALTER TABLE "comment_lens_assessment" ADD COLUMN IF NOT EXISTS "provider_id" text DEFAULT 'google' NOT NULL;
ALTER TABLE "comment_lens_assessment" ADD COLUMN IF NOT EXISTS "prompt_version" text DEFAULT 'v1' NOT NULL;
ALTER TABLE "comment_lens_assessment" ADD COLUMN IF NOT EXISTS "context_scope" text DEFAULT 'comment_and_code' NOT NULL;
ALTER TABLE "comment_lens_assessment" ADD COLUMN IF NOT EXISTS "retention_until" timestamptz;
