"use client";
import { useEffect, useRef, useState } from "react";
import type { CommentKind, ReviewStatus } from "../contracts";
import { ConnectGithub, NoRepositoryAccess, ReadyToScan, ScanFailed, ScanInProgress } from "./dashboard/onboarding";
import { CommentDetail, CommentQueue, FilterPanel, RepositoryContextBar, type Assessment, type FilterState, type QueuePage, type ReviewDecision, type ReviewMutation, type ScanSummary } from "./dashboard/review";

type Repo = { id: string; owner: string; name: string; defaultBranch: string; private: boolean };
type Scan = ScanSummary;
type Phase = "connect_github" | "no_repository_access" | "ready_to_scan" | "scan_in_progress" | "scan_failed" | "review_queue";
async function api<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, { ...init, headers: { "Content-Type": "application/json", ...init?.headers } }); const body = await response.json().catch(() => null) as { error?: { message?: string } } | null; if (!response.ok) throw new Error(body?.error?.message ?? `Request failed (${response.status})`); return body as T; }
function getPhase(repo: Repo | null, scan: Scan | null, error: string): Phase { if (error === "Authentication required") return "connect_github"; if (!repo) return "no_repository_access"; if (!scan) return "ready_to_scan"; if (scan.status === "failed") return "scan_failed"; if (scan.status === "queued" || scan.status === "running") return "scan_in_progress"; return "review_queue"; }
const emptyFilters: FilterState = { query: "", path: "", author: "", minScore: "", maxScore: "", status: "all", language: "all", kind: "all", protected: "all", generated: "all", license: "all", todo: "all" };

export function CommentLensDashboard() {
  const [repos, setRepos] = useState<Repo[]>([]); const [repo, setRepo] = useState<Repo | null>(null); const [scan, setScan] = useState<Scan | null>(null); const [scans, setScans] = useState<Scan[]>([]); const [data, setData] = useState<QueuePage | null>(null); const [selectedId, setSelectedId] = useState<string | null>(null); const [filters, setFilters] = useState<FilterState>(emptyFilters); const [sort, setSort] = useState<"score" | "path" | "age" | "status">("score"); const [page, setPage] = useState(1); const [panel, setPanel] = useState<"filters" | "detail" | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [assessment, setAssessment] = useState<Assessment | null>(null); const [assessmentPending, setAssessmentPending] = useState(false); const [note, setNote] = useState(""); const searchRef = useRef<HTMLInputElement>(null); const triggerRef = useRef<HTMLButtonElement>(null);
  const refresh = () => { setLoading(true); api<{ repositories: Repo[] }>("/api/repositories").then((result) => { setRepos(result.repositories); setRepo(result.repositories[0] ?? null); setError(""); }).catch((cause: unknown) => { setRepos([]); setRepo(null); setError(cause instanceof Error ? cause.message : "Could not load repositories."); }).finally(() => setLoading(false)); };
  useEffect(() => { refresh(); }, []);
  useEffect(() => { if (!repo) return; let active = true; setScan(null); setData(null); setSelectedId(null); api<{ scans: Scan[] }>(`/api/scans?schemaVersion=1&repositoryId=${encodeURIComponent(repo.id)}`).then((result) => { if (active) { setScans(result.scans); setScan(result.scans[0] ?? null); } }).catch((cause: unknown) => { if (active) setError(cause instanceof Error ? cause.message : "Could not load scan history."); }); return () => { active = false; }; }, [repo]);
  useEffect(() => { if (!scan || scan.status === "complete" || scan.status === "failed") return; const timer = window.setInterval(() => { api<Scan>(`/api/scans/${scan.scanId}`).then(setScan).catch(() => undefined); }, 2000); return () => window.clearInterval(timer); }, [scan]);
  useEffect(() => { if (!scan || scan.status !== "complete") return; const params = new URLSearchParams({ schemaVersion: "1", scanId: scan.scanId, page: String(page), pageSize: "50", sort }); for (const [key, value] of Object.entries(filters)) if (value && value !== "all") params.set(key === "path" ? "path" : key, value); setLoading(true); api<QueuePage>(`/api/scans/${scan.scanId}/comments?${params}`).then((result) => { setData(result); setSelectedId((current) => result.items.some((item) => item.commentId === current) ? current : result.items[0]?.commentId ?? null); setError(""); }).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : "Could not load comments.")).finally(() => setLoading(false)); }, [scan, page, filters, sort]);
  useEffect(() => { setPage(1); }, [filters, sort]);
  const selected = data?.items.find((item) => item.commentId === selectedId) ?? null; const decision = data?.decisions.find((item) => item.commentId === selected?.commentId); useEffect(() => setNote(decision?.note ?? ""), [selectedId, decision?.note]); const phase = getPhase(repo, scan, error); const languages = [...new Set(data?.items.map((item) => item.language) ?? [])];
  useEffect(() => { const handler = (event: KeyboardEvent) => { if (event.key === "Escape") { setPanel(null); triggerRef.current?.focus(); return; } const target = event.target; if (target instanceof HTMLElement && (target.matches("input,textarea,select") || target.isContentEditable)) return; if (event.key === "/" && phase === "review_queue") { event.preventDefault(); setPanel("filters"); window.setTimeout(() => searchRef.current?.focus(), 0); } if ((event.key === "j" || event.key === "k") && data?.items.length) { const index = data.items.findIndex((item) => item.commentId === selectedId); const next = Math.max(0, Math.min(data.items.length - 1, index + (event.key === "j" ? 1 : -1))); setSelectedId(data.items[next].commentId); setPanel("detail"); } }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, [data, phase, selectedId]);
  const startScan = async () => { if (!repo) return; try { const result = await api<Scan>("/api/scans", { method: "POST", body: JSON.stringify({ schemaVersion: 1, repositoryId: repo.id, ref: repo.defaultBranch }) }); setScan(result); setScans((current) => [result, ...current.filter((item) => item.scanId !== result.scanId)]); setData(null); setNotice("Scan queued."); setError(""); } catch (cause: unknown) { setError(cause instanceof Error ? cause.message : "Could not start scan."); } };
  const review = async (status: ReviewMutation) => { if (!selected) return; try { const result = await api<{ decision?: ReviewDecision }>(`/api/comments/${selected.commentId}/review`, { method: "PATCH", body: JSON.stringify({ schemaVersion: 1, status, note: note || null }) }); const next = result.decision ?? { commentId: selected.commentId, status, note: note || null }; setData((current) => current ? { ...current, decisions: [...current.decisions.filter((item) => item.commentId !== selected.commentId), next] } : current); setNotice(`Marked ${selected.path} as ${status}.`); } catch (cause: unknown) { setError(cause instanceof Error ? cause.message : "Could not save review."); } };
  const assess = async () => { if (!selected || !scan) return; setAssessmentPending(true); try { const result = await api<{ assessment: Assessment }>(`/api/comments/${selected.commentId}/assessment`, { method: "POST", body: JSON.stringify({ schemaVersion: 1, scanId: scan.scanId, sourceContext: "comment_and_code" }) }); setAssessment(result.assessment); setNotice("Assessment loaded. The deterministic score did not change."); } catch (cause: unknown) { setError(cause instanceof Error ? cause.message : "Assessment unavailable."); } finally { setAssessmentPending(false); } };
  const change = <Key extends keyof FilterState>(key: Key, value: FilterState[Key]) => setFilters((current) => ({ ...current, [key]: value }));
  if (loading && !repos.length && !error) return <main className="shell"><a className="skip-link" href="#main-content">Skip to workspace</a><header className="topbar"><span className="brand"><span className="brand-mark" aria-hidden="true">CL</span><span>Comment Lens</span></span></header><section className="state-surface loading-card" aria-busy="true" aria-label="Loading Comment Lens"><span className="loading-line loading-line-wide" /><span className="loading-line" /></section></main>;
  return <main className="shell"><a className="skip-link" href="#main-content">Skip to workspace</a><header className="topbar"><a className="brand" href="#main-content" aria-label="Comment Lens home" tabIndex={-1}><span className="brand-mark" aria-hidden="true">CL</span><span>Comment Lens</span></a><span className="account">Private review workspace</span></header><div id="main-content" tabIndex={-1} className="dashboard-main">
    {phase === "connect_github" && <ConnectGithub oauthHref="/api/auth/github" />}{phase === "no_repository_access" && <NoRepositoryAccess error={error && error !== "Authentication required" ? error : undefined} onRefresh={refresh} isRefreshing={loading} />}
    {repo && !["connect_github", "no_repository_access"].includes(phase) && <RepositoryContextBar repositories={repos} repository={repo} scan={scan} scans={scans} onRepositoryChange={(id) => setRepo(repos.find((item) => item.id === id) ?? repo)} onScanChange={(id) => { setScan(scans.find((item) => item.scanId === id) ?? null); setData(null); setSelectedId(null); }} />}
    {repo && phase === "ready_to_scan" && <ReadyToScan repositoryName={`${repo.owner}/${repo.name}`} ref={repo.defaultBranch} retentionSummary="Comments and short code context only" onStartScan={startScan} />}{repo && scan && phase === "scan_in_progress" && <ScanInProgress repositoryName={`${repo.owner}/${repo.name}`} ref={scan.resolvedCommit?.slice(0, 12) ?? scan.ref ?? repo.defaultBranch} status={scan.status === "queued" ? "queued" : "running"} />}{repo && scan && phase === "scan_failed" && <ScanFailed repositoryName={`${repo.owner}/${repo.name}`} failureSummary={error || undefined} onRetry={startScan} />}
    {phase === "review_queue" && scan && <><section className="workspace-title"><div><h1>Review workspace</h1><p>Scores prioritize a human review. They do not identify authorship.</p></div><div className="workspace-actions"><button className="button button-secondary" type="button" onClick={() => window.location.assign(`/api/scans/${scan.scanId}/export`)}>Export decisions</button><button className="button button-primary" type="button" onClick={startScan}>Start another scan</button></div></section>{error && <div className="error-banner" role="alert"><strong>Queue update failed.</strong><span>{error}</span></div>}<div className="mobile-controls"><button ref={triggerRef} className="button button-secondary" type="button" onClick={() => setPanel("filters")}>Filters</button><button className="button button-secondary" type="button" disabled={!selected} onClick={() => setPanel("detail")}>Open detail</button></div><div className={`dashboard-grid ${selected ? "has-detail" : ""}`}><FilterPanel open={panel === "filters"} filters={filters} languages={languages} searchRef={searchRef} onChange={change} onClear={() => setFilters(emptyFilters)} onClose={() => setPanel(null)} /><CommentQueue page={data} selectedId={selectedId} sort={sort} loading={loading} onSelect={(id) => { setSelectedId(id); setAssessment(null); setPanel("detail"); }} onSortChange={setSort} onPageChange={setPage} />{selected && <CommentDetail comment={selected} decision={decision} assessment={assessment} note={note} assessmentPending={assessmentPending} open={panel === "detail"} onClose={() => { setPanel(null); triggerRef.current?.focus(); }} onAssess={assess} onNoteChange={setNote} onReview={review} />}</div></>}
  </div><p className="privacy-note">Source files are read-only. Comment Lens retains comments and short context, not complete source files.</p><div className="sr-only" aria-live="polite">{notice}</div></main>;
}
