import { z } from "zod";

export const CONTRACT_SCHEMA_VERSION = 1 as const;
const id = z.string().min(1).max(256);
const hash = z.string().regex(/^[a-f0-9]{64}$/);
const nonNegative = z.number().int().min(0);
const isoDate = z.string().datetime({ offset: true });

export const ParserEngine = z.enum(["tree-sitter", "pygments"]);
export type ParserEngine = z.infer<typeof ParserEngine>;
export const FileStatus = z.enum(["parsed", "parsed_with_errors", "fallback", "excluded", "failed"]);
export type FileStatus = z.infer<typeof FileStatus>;
export const CommentKind = z.enum(["line", "block", "doc_line", "doc_block", "markup", "shebang", "preprocessor", "special", "unknown"]);
export type CommentKind = z.infer<typeof CommentKind>;
export const Placement = z.enum(["file_header", "leading", "inline", "trailing", "standalone"]);
export type Placement = z.infer<typeof Placement>;
export const ReviewStatus = z.enum(["unreviewed", "keep", "rewrite", "delete", "unsure"]);
export type ReviewStatus = z.infer<typeof ReviewStatus>;
export const ReviewMutationStatus = z.enum(["keep", "rewrite", "delete", "unsure"]);
export type ReviewMutationStatus = z.infer<typeof ReviewMutationStatus>;
export const ScoreBand = z.enum(["low", "review", "high", "protected"]);
export type ScoreBand = z.infer<typeof ScoreBand>;
export const DiagnosticCode = z.enum(["unsupported_language", "grammar_missing", "decode_failed", "binary_file", "file_too_large", "permission_denied", "parse_failed", "git_failed"]);
export type DiagnosticCode = z.infer<typeof DiagnosticCode>;

export const SourcePoint = z.object({ line0: nonNegative, columnByte0: nonNegative }).strict();
export type SourcePoint = z.infer<typeof SourcePoint>;
export const SourceSpan = z.object({ startByte: nonNegative, endByte: nonNegative, start: SourcePoint, end: SourcePoint, endExclusive: z.literal(true), precision: z.enum(["exact", "approximate"]) }).strict();
export type SourceSpan = z.infer<typeof SourceSpan>;
export const Diagnostic = z.object({ path: z.string().min(1).nullable(), severity: z.enum(["warning", "error"]), code: DiagnosticCode, message: z.string().min(1).max(2000) }).strict();
export type Diagnostic = z.infer<typeof Diagnostic>;

export const FileRecord = z.object({ path: z.string().min(1), discovery: z.enum(["tracked", "untracked", "explicit"]), language: z.string().min(1).nullable(), status: FileStatus, parser: ParserEngine.nullable(), sizeBytes: nonNegative, contentSha256: hash.nullable(), encoding: z.string().min(1).nullable(), lineCount: nonNegative.nullable(), exclusionReason: z.string().min(1).nullable(), matchedRule: z.string().min(1).nullable(), parseErrorCount: nonNegative }).strict();
export type FileRecord = z.infer<typeof FileRecord>;
export const SymbolRef = z.object({ kind: z.enum(["module", "class", "struct", "function", "method", "property", "block"]), name: z.string().min(1).nullable(), qualifiedName: z.string().min(1).nullable(), signature: z.string().min(1).nullable(), span: SourceSpan }).strict();
export type SymbolRef = z.infer<typeof SymbolRef>;
export const SymbolContext = z.object({ enclosing: SymbolRef.nullable(), attachedTo: SymbolRef.nullable(), resolution: z.enum(["tree-sitter", "none"]) }).strict();
export type SymbolContext = z.infer<typeof SymbolContext>;
export const BlameSpan = z.object({ startLine0: nonNegative, endLine0: nonNegative, commit: z.string().min(1).nullable(), authorName: z.string().min(1).nullable(), authorEmail: z.string().min(1).nullable(), authoredAt: isoDate.nullable(), source: z.enum(["commit", "worktree", "unavailable"]) }).strict();
export type BlameSpan = z.infer<typeof BlameSpan>;
export const GitContext = z.object({ available: z.boolean(), primaryCommit: z.string().min(1).nullable(), blameSpans: z.array(BlameSpan), error: z.string().min(1).nullable() }).strict();
export type GitContext = z.infer<typeof GitContext>;
export const Finding = z.object({ ruleId: z.string().min(1), contribution: z.number().finite().min(0), evidence: z.record(z.string(), z.union([z.string(), z.number().finite(), z.boolean(), z.null(), z.array(z.string())])), explanation: z.string().min(1).max(2000) }).strict();
export type Finding = z.infer<typeof Finding>;
export const HeuristicScore = z.object({ eligible: z.boolean(), priorityScore: z.number().finite().min(0).max(100).nullable(), band: ScoreBand, ruleSetVersion: z.string().min(1), findings: z.array(Finding).max(32) }).strict();
export type HeuristicScore = z.infer<typeof HeuristicScore>;
export const CommentRecord = z.object({ commentId: id, scanId: id, path: z.string().min(1), language: z.string().min(1), kind: CommentKind, placement: Placement, rawText: z.string().min(1).max(65536), bodyText: z.string().max(65536), rawSpan: SourceSpan, bodySpan: SourceSpan.nullable(), fragments: z.array(SourceSpan).max(256), tags: z.array(z.string().min(1)).max(32), parser: ParserEngine, symbol: SymbolContext.nullable(), sourceContext: z.string().max(8192).nullable(), git: GitContext, score: HeuristicScore }).strict();
export type CommentRecord = z.infer<typeof CommentRecord>;

export const ScanManifest = z.object({ schemaVersion: z.literal(CONTRACT_SCHEMA_VERSION), scanId: id, repoId: id, sourceMode: z.enum(["worktree", "revision"]), headCommit: z.string().min(1).nullable(), worktreeFingerprint: z.string().min(1), configHash: hash, extractorVersion: z.string().min(1), parserVersions: z.record(z.string(), z.string().min(1)), startedAt: isoDate, completedAt: isoDate, files: z.array(FileRecord), diagnostics: z.array(Diagnostic) }).strict();
export type ScanManifest = z.infer<typeof ScanManifest>;
export const ReviewDecision = z.object({ commentId: id, status: ReviewStatus, note: z.string().max(4000).nullable(), updatedAt: isoDate }).strict();
export type ReviewDecision = z.infer<typeof ReviewDecision>;
export const WorkerChunkPayload = z.object({ schemaVersion: z.literal(CONTRACT_SCHEMA_VERSION), scanId: id, chunkId: id, sequence: nonNegative, totalChunks: z.number().int().min(1), comments: z.array(CommentRecord), files: z.array(FileRecord), diagnostics: z.array(Diagnostic) }).strict().superRefine((value, context) => { if (value.sequence >= value.totalChunks) context.addIssue({ code: z.ZodIssueCode.custom, path: ["sequence"], message: "sequence must be less than totalChunks" }); });
export type WorkerChunkPayload = z.infer<typeof WorkerChunkPayload>;
export const WorkerCompletePayload = z.object({ schemaVersion: z.literal(CONTRACT_SCHEMA_VERSION), scanId: id, manifest: ScanManifest, commentCount: nonNegative, fileCount: nonNegative, chunkCount: z.number().int().min(1), contentSha256: hash }).strict();
export type WorkerCompletePayload = z.infer<typeof WorkerCompletePayload>;
export const WorkerChunkResponse = z.object({ schemaVersion: z.literal(CONTRACT_SCHEMA_VERSION), accepted: z.literal(true), duplicate: z.boolean().optional(), chunkId: id }).strict();
export type WorkerChunkResponse = z.infer<typeof WorkerChunkResponse>;
export const WorkerCompleteResponse = z.object({ schemaVersion: z.literal(CONTRACT_SCHEMA_VERSION), accepted: z.literal(true), status: z.literal("complete") }).strict();
export type WorkerCompleteResponse = z.infer<typeof WorkerCompleteResponse>;
export const WorkerFailurePayload = z.object({ schemaVersion: z.literal(CONTRACT_SCHEMA_VERSION), scanId: id, reason: z.string().min(1).max(2000) }).strict();
export type WorkerFailurePayload = z.infer<typeof WorkerFailurePayload>;
export const WorkerFailureResponse = z.object({ schemaVersion: z.literal(CONTRACT_SCHEMA_VERSION), accepted: z.literal(true), status: z.literal("failed") }).strict();
export type WorkerFailureResponse = z.infer<typeof WorkerFailureResponse>;

export const RepositoryRef = z.object({ id, owner: z.string().min(1), name: z.string().min(1), defaultBranch: z.string().min(1), private: z.boolean() }).strict();
export type RepositoryRef = z.infer<typeof RepositoryRef>;
export const RepositoryListResponse = z.object({ schemaVersion: z.literal(CONTRACT_SCHEMA_VERSION), repositories: z.array(RepositoryRef) }).strict();
export type RepositoryListResponse = z.infer<typeof RepositoryListResponse>;
export const ScanCreateRequest = z.object({ schemaVersion: z.literal(CONTRACT_SCHEMA_VERSION), repositoryId: id, ref: z.string().min(1).max(256), includeUntracked: z.boolean().optional().default(false) }).strict();
export type ScanCreateRequest = z.infer<typeof ScanCreateRequest>;
export const ScanCreateResponse = z.object({ schemaVersion: z.literal(CONTRACT_SCHEMA_VERSION), scanId: id, status: z.enum(["queued", "running"]) }).strict();
export type ScanCreateResponse = z.infer<typeof ScanCreateResponse>;
export const ScanStatus = z.enum(["queued", "running", "complete", "failed"]);
export type ScanStatus = z.infer<typeof ScanStatus>;
const ApiScanDiagnostic = z.object({ code: z.string().min(1).max(128), message: z.string().min(1).max(2000).optional() }).passthrough();
export const ScanRecord = z.object({ schemaVersion: z.literal(CONTRACT_SCHEMA_VERSION), scanId: id, repository: z.string().min(1), ref: z.string().min(1), resolvedCommit: z.string().min(1).nullable(), status: ScanStatus, commentCount: nonNegative, fileCount: nonNegative, chunkCount: nonNegative, diagnostics: z.array(ApiScanDiagnostic), createdAt: isoDate, completedAt: isoDate.nullable() }).strict();
export type ScanRecord = z.infer<typeof ScanRecord>;
export const ScanListQuery = z.object({ schemaVersion: z.literal(CONTRACT_SCHEMA_VERSION), repositoryId: id, limit: z.number().int().min(1).max(50).default(20) }).strict();
export type ScanListQuery = z.infer<typeof ScanListQuery>;
export const ScanListResponse = z.object({ schemaVersion: z.literal(CONTRACT_SCHEMA_VERSION), scans: z.array(ScanRecord) }).strict();
export type ScanListResponse = z.infer<typeof ScanListResponse>;
export const CommentQuery = z.object({ schemaVersion: z.literal(CONTRACT_SCHEMA_VERSION), scanId: id, q: z.string().max(200).optional(), status: ReviewStatus.optional(), language: z.string().max(64).optional(), kind: CommentKind.optional(), path: z.string().max(512).optional(), minScore: z.number().finite().min(0).max(100).optional(), maxScore: z.number().finite().min(0).max(100).optional(), author: z.string().max(256).optional(), protected: z.boolean().optional(), generated: z.boolean().optional(), license: z.boolean().optional(), todo: z.boolean().optional(), sort: z.enum(["score", "path", "age", "status"]).default("score"), page: z.number().int().min(1).default(1), pageSize: z.number().int().min(1).max(100).default(50) }).strict().superRefine((value, context) => { if (value.minScore !== undefined && value.maxScore !== undefined && value.minScore > value.maxScore) context.addIssue({ code: z.ZodIssueCode.custom, path: ["minScore"], message: "minScore must not exceed maxScore" }); });
export type CommentQuery = z.infer<typeof CommentQuery>;
export const CommentPageResponse = z.object({ schemaVersion: z.literal(CONTRACT_SCHEMA_VERSION), items: z.array(CommentRecord), decisions: z.array(ReviewDecision), page: z.number().int().min(1), pageSize: z.number().int().min(1).max(100), total: nonNegative, hasNextPage: z.boolean(), nextPage: z.number().int().min(1).nullable() }).strict();
export type CommentPageResponse = z.infer<typeof CommentPageResponse>;
export const ReviewDecisionRequest = z.object({ schemaVersion: z.literal(CONTRACT_SCHEMA_VERSION), status: ReviewMutationStatus, note: z.string().max(4000).nullable().optional() }).strict();
export type ReviewDecisionRequest = z.infer<typeof ReviewDecisionRequest>;
export const ReviewDecisionResponse = z.object({ schemaVersion: z.literal(CONTRACT_SCHEMA_VERSION), decision: ReviewDecision }).strict();
export type ReviewDecisionResponse = z.infer<typeof ReviewDecisionResponse>;

export const AssessmentLabel = z.enum(["ordinary", "template_like", "overexplained", "uncertain", "protected"]);
export const GeminiAssessmentOutput = z.object({ schemaVersion: z.literal(CONTRACT_SCHEMA_VERSION), commentId: id, providerId: z.string().min(1), modelId: z.string().min(1), promptVersion: z.string().min(1), styleLabel: AssessmentLabel, confidence: z.number().finite().min(0).max(1), reasons: z.array(z.string().min(1).max(1000)).min(1).max(3), suggestedRewrite: z.string().max(65536).nullable(), assessedAt: isoDate }).strict();
export type GeminiAssessmentOutput = z.infer<typeof GeminiAssessmentOutput>;
export const AssessmentRequest = z.object({ schemaVersion: z.literal(CONTRACT_SCHEMA_VERSION), scanId: id, sourceContext: z.enum(["comment_only", "comment_and_symbol", "comment_and_code"]).default("comment_and_code") }).strict();
export type AssessmentRequest = z.infer<typeof AssessmentRequest>;
export const AssessmentResponse = z.object({ schemaVersion: z.literal(CONTRACT_SCHEMA_VERSION), assessment: GeminiAssessmentOutput }).strict();
export type AssessmentResponse = z.infer<typeof AssessmentResponse>;
export const ErrorResponse = z.object({ schemaVersion: z.literal(CONTRACT_SCHEMA_VERSION), error: z.object({ code: z.enum(["invalid_request", "unauthenticated", "forbidden", "not_found", "conflict", "invalid_signature", "stale_request", "incompatible_schema", "scan_failed", "internal_error"]), message: z.string().min(1).max(1000), requestId: id }).strict() }).strict();
export type ErrorResponse = z.infer<typeof ErrorResponse>;
export const WorkerRequestHeaders = z.object({ "x-comment-lens-timestamp": z.string().regex(/^[0-9]+$/), "x-comment-lens-signature": z.string().regex(/^sha256=[a-f0-9]{64}$/), "x-comment-lens-chunk-id": id }).strict();
export type WorkerRequestHeaders = z.infer<typeof WorkerRequestHeaders>;
